version: "3.3"
services:
  driver:
   image: zhivkopetrov90/robotics_accelerator_2022:driver_img
   privileged: true
   environment:
    - DISPLAY=:1
   networks:
    static_test_net:
     ipv4_address: 192.168.56.1
   ports:
      - "5566:5566"
   devices:
     - "/tmp/ttyUR:/tmp/ttyUR"
   depends_on:
      - "ursim"
  ursim:
   image: zhivkopetrov90/robotics_accelerator_2022:ursim_img
   privileged: true
   environment:
    - ROBOT_MODEL=UR10e
    - DISPLAY=:1
   networks:
    static_test_net:
     ipv4_address: 192.168.56.101
   ports:
      - "5900:5900"
      - "29999:29999"
      - "8080:8080"
      - "30001-30004:30001-30004"
   volumes:
      - ./ursim/aux/.vol/:/ursim/programs
networks:
 static_test_net:
  driver: bridge
  ipam:
   config:
    - subnet: 192.168.0.0/16